version: '3'
services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile  # Dockerfileからビルドする
    ports:
      - '1111:1111'
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./work:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''
